apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: infra-bot
  template:
    metadata:
      labels:
        app: infra-bot
    spec:
      containers:
        - name: infra-bot
          image: 427071048654.dkr.ecr.us-west-2.amazonaws.com/simple-app-repo:latest
          ports:
            - containerPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra-bot-ingress
spec:
  rules:
    - host: eks-lb-ext-1050542204.us-west-2.elb.amazonaws.com
      http:
        paths:
          - path: /path
            pathType: Prefix
            backend:
              service:
                name: infra-bot-service
                port:
                  number: 80

