apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: updated-hello-world
  template:
    metadata:
      labels:
        app: updated-hello-world
    spec:
      containers:
        - name: hello-world
          image: 427071048654.dkr.ecr.us-west-2.amazonaws.com/simple-app-repo:latest
          ports:
            - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
spec:
  rules:
    - host: gregs-infra-testing-bot.com
      http:
        paths:
          - path: /path
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 80

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80










