apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage-app
  template:
    metadata:
      labels:
        app: webpage-app
    spec:
      containers:
        - name: webpage-app
          image: 427071048654.dkr.ecr.us-west-2.amazonaws.com/simple-app-repo:latest
          ports:
            - containerPort: 80


--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  rules:
    - host: gregs-testing-infra-bot.com
      http:
        paths:
          - path: /first
            pathType: Prefix
            backend:
              service:
                name: webpage-app
                port:
                  number: 80













