apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: infra-bot
  template:
    metadata:
      labels:
        app: infra-bot
    spec:
      containers:
        - name: infra-bot
          image: 427071048654.dkr.ecr.us-west-2.amazonaws.com/simple-app-repo:latest
          ports:
            - containerPort: 80
