apiVersion: v1
kind: Namespace
metadata:
  name: default


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage-app 
  template:
    metadata:
      labels:
        app: webpage-app 
    spec:
      containers:
      - image: 427071048654.dkr.ecr.us-west-2.amazonaws.com/simple-app-repo:latest
        name: webpage-app
        ports:
        - containerPort: 5000
















