apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx  # Use the same namespace
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80