apiVersion: v1
kind: Service
metadata:
  name: webpage-app-service
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  namespace: default
spec:
  selector:
    app: webpage-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer



    
