apiVersion: v1
kind: Service
metadata:
  name: webpage-app-service
  namespace: default
spec:
  selector:
    app: webpage-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer



    
