apiVersion: v1
kind: Service
metadata:
  name: webpage-app-service
  namespace: nginx
spec:
  selector:
    app: webpage-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

    
