name: Kubernetes Workflow

on:
  pull_request:
    branches: main
  push:
    branches: main 
  workflow_run:
    workflows: ["Terraform Workflow Merge"]
    types:
      - completed

permissions:
  id-token: write
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::427071048654:role/github-actions-admin
          role-session-name: k8sdeploysession
          aws-region: us-west-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
              docker buildx create --use
              docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --platform linux/amd64 -f ./application/app/Dockerfile -t 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com/simple-app-repo:latest . --load
              docker images --filter reference=simple-app-repo
              aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com
              docker push 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com/simple-app-repo:latest
        
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-west-2 --name testing-eks-cluster --kubeconfig ${{ runner.workspace }}/application/k8s/.kube/config --alias kube-admin
          kubectl config get-contexts
          kubectl config use-context kube-admin
        env:
          KUBECONFIG: ${{ runner.workspace }}/application/k8s/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./application/k8s/deployment.yaml --kubeconfig ${{ runner.workspace }}/application/k8s/.kube/config 
          kubectl apply -f ./application/k8s/service.yaml --kubeconfig ${{ runner.workspace }}/application/k8s/.kube/config 
          kubectl apply -f ./application/k8s/configmap.yaml --kubeconfig ${{ runner.workspace }}/application/k8s/.kube/config
          kubectl apply -f ./application/k8s/nginx.yaml --kubeconfig ${{ runner.workspace }}/application/k8s/.kube/config

      # - name: Delete old deployments
      #   run: |
      #       CURRENT_DEPLOYMENT="webpage-app"
      #       NAMESPACE="default"
      #       kubectl get deployments -n $NAMESPACE -o custom-columns=":metadata.name" --no-headers | \
      #         grep -v "$CURRENT_DEPLOYMENT" | \
      #         xargs -I {} kubectl delete deployment {} -n $NAMESPACE
      #   env:
      #       KUBECONFIG: ${{ runner.workspace }}/application/k8s/.kube/config
      
      - name: Delete testing pods over 24 hours
        run: |
            kubectl get pods -n default -o json | \
              jq -r '.items[] | select(((now - (.metadata.creationTimestamp | fromdate)) / 3600) >= 24) | .metadata.name' | \
              xargs -I {} kubectl delete pod {} -n default
        env:
            KUBECONFIG: ${{ runner.workspace }}/application/k8s/.kube/config
