name: Deploy to Kubernetes

on:
  pull_request:
      branches: main
  push:
    branches: main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
       - name: configureawscredentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           role-to-assume: arn:aws:iam::427071048654:role/github-actions-admin
           role-session-name: k8sdeploysession
           aws-region: ${{env.AWS_DEFAULT_REGION}}
    
       - name: Checkout
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Build and push Docker image
         run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64 -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-python-app:${{ github.sha }} .
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my-python-app:${{ github.sha }}
         env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


       - name: Set up kubectl
         uses: azure/setup-kubectl@v1
         with:
           install-missing: true
           version: latest

       - name: Deploy to Kubernetes
         run: |
           kubectl apply -f k8s/deployment.yaml
           kubectl apply -f k8s/service.yaml
