name: Kubernetes Workflow

on:
  pull_request:
    branches: main
  push:
    branches: main  

permissions:
  id-token: write
  contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2

    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::427071048654:role/github-actions-admin
          role-session-name: k8sdeploysession
          aws-region: us-west-2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
              docker buildx create --use
              docker buildx build --build-arg BUILDKIT_INLINE_CACHE=1 --platform linux/amd64 -f ./application/app/Dockerfile -t 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com/simple-app-repo:${{ github.sha }} . --load
              aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com
              docker push 427071048654.dkr.ecr.${AWS_REGION}.amazonaws.com/simple-app-repo:${{ github.sha }}
        
      - name: Configure kubectl
        run: |
                aws eks --region us-west-2 update-kubeconfig --name dev-eks-cluster
        env:
          KUBECONFIG: ${{ runner.workspace }}./application/k8s/.kube/config 


      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          install-missing: true
          version: latest
          kubeconfig: ./../application/k8s/.kube/config 

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

