# .github/workflows/terraform.yml
name: Terraform Workflow

on:
  pull_request:
      branches: main
  push:
    branches: main  

permissions:
    id-token: write
    contents: read

jobs:
      deploy:
        runs-on: ubuntu-latest
    
        env:
          AWS_DEFAULT_REGION: us-west-2
    
        steps:
           - name: configureawscredentials
             uses: aws-actions/configure-aws-credentials@v1
             with:
               role-to-assume: arn:aws:iam::427071048654:role/github-actions-admin
               role-session-name: k8sdeploysession
               aws-region: ${{env.AWS_DEFAULT_REGION}}
        
           - name: Checkout
             uses: actions/checkout@v2

           - name: Set up Terraform
             uses: hashicorp/setup-terraform@v1
             with: 
              terraform_version:  1.5.0

           - name: Initialize Terraform
             run: terraform init
             working-directory: infrastructure/dev-env

           - name: Plan Terraform changes
             run: terraform plan -out=tfplan
             working-directory: infrastructure/dev-env

           - name: Confirm Terraform apply
             run: |
               read -p "Do you want to apply the Terraform changes? (yes/no): " confirm
               if [ "$confirm" != "yes" ]; then
                 echo "Terraform apply was not confirmed. Exiting..."
                 exit 0
               fi
             shell: bash
             working-directory: infrastructure/dev-env
     
           - name: Apply Terraform changes
             run: terraform apply tfplan
             working-directory: infrastructure/dev-env

             # Add additional steps for testing and deploying your application
