# .github/workflows/terraform.yml
name: Terraform Workflow

on:
  pull_request:
      branches: main
  push:
    branches: main  

permissions:
    id-token: write
    contents: read

jobs:
      deploy:
        runs-on: ubuntu-latest
    
        env:
          AWS_DEFAULT_REGION: us-east-1
    
        steps:
           - name: configureawscredentials
             uses: aws-actions/configure-aws-credentials@v1
             with:
               role-to-assume: arn:aws:iam::427071048654:role/github-actions-admin
               role-session-name: k8sdeploysession
               aws-region: ${{env.AWS_DEFAULT_REGION}}
        
           - name: Checkout
             uses: actions/checkout@v2

           - name: Set up Terraform
             uses: hashicorp/setup-terraform@v1
             with: 
              terraform_version:  1.5.0

           - name: Initialize Terraform
             run: terraform init -chdir=/infrastructure/dev-env

           - name: Plan Terraform changes
             run: terraform plan -chdir=/infrastructure/dev-env -out=tfplan

           - name: Apply Terraform changes
             run: terraform apply tfplan

      # Add additional steps for testing and deploying your application
